# Generated by Django 5.1.6 on 2025-03-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_project_pathways_project_tools_and_more'),
        ('tools', '0003_auto_20250318_2044'),
    ]

    operations = [
    ]
