# Generated by Django 5.1.6 on 2025-03-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_remove_tool_pathways_remove_project_pathways_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='projects', to='tools.tool'),
        ),
    ]
